/**
 * Created by LXL on 2016/5/10.
 */

var _GLOBAL_CHART_TYPE_BAR_BASE = 1;
var _GLOBAL_CHART_TYPE_BAR_HORIZONTAL = 2;
var _GLOBAL_CHART_TYPE_BAR_ACCUMULATIVE  = 3;
var _GLOBAL_CHART_TYPE_BAR_ACCUMULATIVE_HORIZONTAL = 4;
var _GLOBAL_CHART_TYPE_LINE_BASE = 5;
var _GLOBAL_CHART_TYPE_LINE_HORIZONTAL = 6;
var _GLOBAL_CHART_TYPE_LINE_ACCUMULATIVE = 7;
var _GLOBAL_CHART_TYPE_LINE_STACKED_AREA = 8;
var _GLOBAL_CHART_TYPE_PIE_BASE = 9;
var _GLOBAL_CHART_TYPE_PIE_NIGHTINGALL = 10;
var _GLOBAL_CHART_TYPE_PIE_ANNULUS = 11;
